### ISSUE TITLE
Problem loading the pretrained model in PCN

### ISSUE THREAD

**Issue by himmetozcan** [vinits5/learning3d#18]
Hi there. Thanks for this repository.
I think there are some problems in model constructions, the model files and pretrained model dictionary seem to be not matching.
I see problems while loading a pretrained model. Such as in point completion network:

```
from learning3d.models import PCN
import torch
pcn = PCN()
pcn.load_state_dict(torch.load('learning3d/pretrained/exp_pcn/models/best_model.t7', map_location='cpu'))
```

and this is the error I get:

```
RuntimeError: Error(s) in loading state_dict for PCN:
        Missing key(s) in state_dict: "conv5.weight", "conv5.bias", "conv6.weight", "conv6.bias", "conv7.weight", "conv7.bias". 

```

Do you know what the problem is in here?

**Comment by vinits5** [comment]
Really sorry for the delayed response @himmetozcan. The problem has been resolved with my new commit (https://github.com/vinits5/learning3d/commit/0ba6e5cf926e161c3604ddccecc4ce480e3885c3).
This issue was occurring as the default value of detailed_output argument to PCN class was set as True. While the pretrained model doesn't provide detailed output (~16000 points). I have updated the default value to False now. So, it won't raise any error now. Attaching a screenshot to show the updated results.
![Screenshot from 2023-06-11 18-23-49](https://github.com/vinits5/learning3d/assets/26848325/d1ca65d6-9522-4231-9f59-4878d48adf68)
